# Generated by Django 4.2.1 on 2023-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_store_city_alter_store_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
